### ISSUE TITLE
As a developer, I would like to add every useful workflow inside this repository

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/devops#31]
## Executive summary

This directory does not have any workflows. Without a workflow, it is difficult to manage the code quality of the project.

## Context

In most of our directories, we have workflows in place to manage the code quality that is found on the main branch. Here, we need to do the same thing.

## TODO

- [x] Add this workflow https://github.com/ai-cfia/github-workflows/blob/main/.github/workflows/workflow-lint-test-python.md
- [x] Add this workflow https://github.com/ai-cfia/github-workflows/blob/main/.github/workflows/workflow-repo-standards-validation.yml
- [x] Add this workflow https://github.com/ai-cfia/github-workflows/blob/main/.github/workflows/workflow-markdown-check.md

**Comment by ThomasCardin** [comment]
Add the python workflow inside this PR https://github.com/ai-cfia/devops/pull/27
